version: "3.8"

services:
  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - redis_data:/data

  app:
    image: tarun08code/url-shortener:latest  # Changed from 'build: .'
    container_name: url-shortener
    ports:
      - "3000:3000"
    depends_on:
      - redis

volumes:
  redis_data: